### ISSUE TITLE
Allow exclude folders

### ISSUE THREAD

**Issue by simonbcn** [graysky2/lostfiles#35]
Hi,
I have a folder `/multimedia` with movies and series. `lostfiles` doesn't should check this folder.

**Comment by ArchangeGabriel** [comment]
Wouldn’t it be more simple to replace the `find /` with something like `find /boot /etc /opt /usr /srv /var` (even keeping the `/var/*` excludes if you like)?

Packages in Arch are not supposed to include files in any other places AFAIK, `/srv` itself is only relevant for 6 packages in Arch repos (and I’m wondering whether this is supposed to be used actually) and `/opt` is used by 38 packages in the repos, but accordingly much more in AUR.

I’m also asking about this because for instance I have things under `/backup` that get eat by lostfiles, and I believe there is no need to get more complicated by allowing excludes if you could just clean the base list.

**Comment by graysky2** [comment]
@ArchangeGabriel - Might be a better way... PRs are welcomed.

**Comment by ArchangeGabriel** [comment]
#40

**Comment by ArchangeGabriel** [comment]
Well this does not really closes this issue. I think lostfiles should check a list of paths to exclude at `/etc/lostfiles.conf`, because people (at least me) might want to exclude some things from the strict mode without going to the standard mode. I just don’t have sufficient knowledge to code that.

**Comment by graysky2** [comment]
@ArchangeGabriel - Defining them in an array might work but then we would need to add a check to make sure they are valid paths to avoid errors.  Not sure how to add wildcards.. nor how to go about printing out an entry in the `-wholename '${arraymember}' -prune -o \` format...

Let's keep this open as a place holder

**Comment by graysky2** [comment]
This has been implemented in the current dev branch.
