### ISSUE TITLE
Some folders/files to exclude

### ISSUE THREAD

**Issue by simonbcn** [graysky2/lostfiles#36]
I think these folders and files should be excluded:
```
/usr/lib/gdk-pixbuf-2.0/*/loaders.cache
/usr/lib/gio/modules/giomodule.cache
/usr/lib/gtk-2.0/*/immodules.cache
/usr/lib/gtk-3.0/*/immodules.cache
/usr/lib/modules/*/kernel/misc
/usr/lib/udev/hwdb.bin
/usr/share/fonts/*/fonts.dir
/usr/share/fonts/*/fonts.scale
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/hplip/base/__pycache__
/usr/share/icons/*/icon-theme.cache
/usr/share/polkit-1/actions/org.gnome.gedit.policy
/usr/share/polkit-1/actions/org.gnome.nautilus.policy
```

About this folder `/usr/share/.mono/new-certs/Trust` I have doubts. I don't know what it's used for.

**Comment by joanbm** [comment]
I also get the .mono certificate files, I think that it's generated after installing mono through pacman by a script, at least it seems to print things related to the certificates to the console. I think it should be excluded.

I also have the following files from CUPS, I think they should be excluded as well:

/etc/cups/ppd/*.ppd
/etc/cups/ppd/*.ppd.O
/etc/cups/printers.conf.O
/etc/printcap

**Comment by joanbm** [comment]
I have forked this repo in order to remove all the extra files in my system. With this, I no longer see any unknown file in `lostfiles relaxed`:

https://github.com/joanbm/lostfiles/commit/6b3bca485cb3213589f560f0c1f5c70ce7840605

Of course, feel free to integrate this into the main repo.

Notes:

* I have added a few files more not listed in any of the comments above (e.g. for TexLive, Docker, etc.).

* I can't discard that some of the files I have excluded are false positives (leftovers from old packages), since my install is pretty old, but most or all of them should be true positives. Would be useful for people to check if they also have the same files from newish installs.

* I didn't exclude those listed in the OP since I didn't find them in my system, even though I have `linux`, `hplip` and `gedit` installed (not sure about the `nautilus` one that is similar to the `gedit` one as well):

    /usr/lib/modules/*/kernel/misc
    /usr/share/hplip/base/__pycache__
    /usr/share/polkit-1/actions/org.gnome.gedit.policy
    /usr/share/polkit-1/actions/org.gnome.nautilus.policy

**Comment by graysky2** [comment]
This can be a slippery slope.  What criteria should be used to put things on an ignore list?  What scope, etc.

**Comment by ArchangeGabriel** [comment]
@graysky2 There is #42 to solve this issue at user level: everyone is responsible for what they want to exclude.

**Comment by graysky2** [comment]
@ArchangeGabriel - I am aware of your PR, I just need to review your work.  I will try to make time this weekend.
