### ISSUE TITLE
Removing Files/Programs that were installed without Pacman

### ISSUE THREAD

**Issue by ndalliard** [graysky2/lostfiles#9]
This is a feature request. I have no idea if this would be easy to integrate. But I wanted to mention it.

It would be great, if the user can remove programs/files that he has installed without pacman from the output of lostfiles. For example I installed do_snapshot by hand and at the moment when I run lostfiles, the output is like 1.500 files from do_snapshots and just 10 which are interesting for me.

I know about that grep thing, but I really dont know how to use it. Maybe its just a little command I have to add that filters everything out from the output that contains do_snapshot for example.

Any idea? Thanks for this little cool script. :+1:

**Comment by graysky2** [comment]
Sorry, but the script is just for identifying files; you can then decide which ones needs to be removed.  An option to do it automatically would be far too dangerous.

**Comment by ndalliard** [comment]
Oh no, I just meant to remove them from the output not from the system. That should be possible with grep or something similar. I just dont know these tools that good at the moment.

**Comment by graysky2** [comment]
Sorry, I misread your request.  I'm not sure how to easily accomplish that.  I guess my push back to you is to simply write a PKGBUILD for said software and install it with pacman.  Why would you want unmanaged files floating around the filesystem?

**Comment by ndalliard** [comment]
Ah, actually a good point and I would learn how to write a PKGBUILD. Great answer, I think I will do that sooner or later. Thanks!

**Comment by wifiextender** [comment]
@ndalliard Create a custom repo and point in your **/etc/pacman.conf**. Whenever you download and or compile program/library from source code the generated package will reside in your repo, thus allowing the package to be upgraded by pacman whenever there is a new version and you are tired to compile it at the moment. Additionally you can create gpg public and private keys to sign those packages in order to ensure that your packages has not been modified, and you'll have to exchange the **SigLevel** to "PackageRequired". I've wrote about that in my [blog](https://wifiextender.github.io/post/custom_repo_with_signed_packages/) recently.
